version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  python:
    build: ./python
    volumes:
      - ./src:/usr/src/app/src
